// <auto-generated />
using CSCI511_Project_4;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSCI511_Project_4.Migrations
{
    [DbContext(typeof(CSCI511_Proj4_DB))]
    [Migration("20211202200957_StartingOut2")]
    partial class StartingOut2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CSCI511_Project_4.Dog", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Did");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("CSCI511_Project_4.Examine", b =>
                {
                    b.Property<int>("Vid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Did")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DogDid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeterinarianVid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Vid", "Did");

                    b.HasIndex("DogDid");

                    b.HasIndex("VeterinarianVid");

                    b.ToTable("Examines");
                });

            modelBuilder.Entity("CSCI511_Project_4.Veterinarian", b =>
                {
                    b.Property<int>("Vid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Vid");

                    b.ToTable("Veterinarians");
                });

            modelBuilder.Entity("CSCI511_Project_4.Examine", b =>
                {
                    b.HasOne("CSCI511_Project_4.Dog", "Dog")
                        .WithMany("Examines")
                        .HasForeignKey("DogDid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSCI511_Project_4.Veterinarian", "Veterinarian")
                        .WithMany("Examines")
                        .HasForeignKey("VeterinarianVid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("CSCI511_Project_4.Dog", b =>
                {
                    b.Navigation("Examines");
                });

            modelBuilder.Entity("CSCI511_Project_4.Veterinarian", b =>
                {
                    b.Navigation("Examines");
                });
#pragma warning restore 612, 618
        }
    }
}
